// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUtP3yz8wbR67VD9MNPGVH3TceJBHA-WQ',
    appId: '1:1029552906373:web:028e525486f7c25dcd09ec',
    messagingSenderId: '1029552906373',
    projectId: 'gss-db-df40f',
    authDomain: 'gss-db-df40f.firebaseapp.com',
    storageBucket: 'gss-db-df40f.firebasestorage.app',
    measurementId: 'G-2XFBYPBC87',

    databaseURL: 'https://gss-db-df40f-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR1rxdT97HbbpyH4cnewJ2-VujTtklWfM',
    appId: '1:1029552906373:android:fb6ecf3b6f5e5b72cd09ec',
    messagingSenderId: '1029552906373',
    projectId: 'gss-db-df40f',
    storageBucket: 'gss-db-df40f.firebasestorage.app',

    databaseURL: 'https://gss-db-df40f-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAy9NY7kAnZy6D907BKLAnIjpUj4fZ7x8',
    appId: '1:1029552906373:ios:11339c3c2e5910fecd09ec',
    messagingSenderId: '1029552906373',
    projectId: 'gss-db-df40f',
    storageBucket: 'gss-db-df40f.firebasestorage.app',
    iosBundleId: 'com.example.gss',

    databaseURL: 'https://gss-db-df40f-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAy9NY7kAnZy6D907BKLAnIjpUj4fZ7x8',
    appId: '1:1029552906373:ios:11339c3c2e5910fecd09ec',
    messagingSenderId: '1029552906373',
    projectId: 'gss-db-df40f',
    storageBucket: 'gss-db-df40f.firebasestorage.app',
    iosBundleId: 'com.example.gss',

    databaseURL: 'https://gss-db-df40f-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUtP3yz8wbR67VD9MNPGVH3TceJBHA-WQ',
    appId: '1:1029552906373:web:6b8de9abdcadc9edcd09ec',
    messagingSenderId: '1029552906373',
    projectId: 'gss-db-df40f',
    authDomain: 'gss-db-df40f.firebaseapp.com',
    storageBucket: 'gss-db-df40f.firebasestorage.app',
    measurementId: 'G-D8TPRB31W2',

    databaseURL: 'https://gss-db-df40f-default-rtdb.firebaseio.com/'
  );
}
